services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4300:4300"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/survivor
    depends_on:
      - mongo
    command: npm run dev:watch

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - .:/app
      - mongo_data:/data/db

volumes:
  mongo_data:
